### ISSUE TITLE
Replace MBED with LPC176x controller

### ISSUE THREAD

**Issue by henrique-silva** [lnls-dig/rffe-hw#3]
Using a MBED board here is a real overkill, since we only use some basic functions provided by it.
We could replace the MBED with a single LPC176x (1768 is the more suitable probably, 1769 for clocks up to 120MHz) and, with just some resistors added, we would have the same functionality.
This change would untie us from a specific product such as MBED and significantly reduce production costs.

The firmware would not need any changes if the pinout is the same as MBED, but we would lose the ability to flash the firmware via USB (drag'n'drop).
We could also use here [openMMC](https://github.com/lnls-dig/openMMC) and reimplement the current logic in separated modules, but this firmware doesn't have a fully tested Ethernet interface yet.

**Comment by aylons** [comment]
This is being addresd by https://github.com/lnls-dig/rffe-uc-hw/
